name: me_cuido
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  flutter_svg: ^0.17.3+1
  url_launcher: ^3.0.3
  firebase_auth:
  google_sign_in:
  firebase_storage: ^2.1.0
  cloud_firestore: ^0.9.13
  generic_bloc_provider: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans-Regular.ttf
        - asset: assets/fonts/NunitoSans/NunitoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NunitoSans/NunitoSans-Bold.ttf
          weight: 700

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
